#!/usr/bin/env bash
# Maintainer: joekamprad [joekamprad //a_t// endeavouros.com]
# Adapted for Fedora
username="$1"
REPO_DIR="endeavouros-i3wm-setup-for-fedora"
git clone https://github.com/Leandro-Michail-Krikis/endeavouros-i3wm-setup-for-fedora.git
REPO_FULL_PATH="$(pwd)/${REPO_DIR}"
cd "${REPO_DIR}/etc/skel/" || exit 1
cp -R .config .local "/home/$username/"
cp .Xresources .gtkrc-2.0 .profile "/home/$username/"
if [ -f set_once.sh ]; then cp set_once.sh "/home/$username/"; fi
if [ -f xed.dconf ]; then cp xed.dconf "/home/$username/"; fi
cd /
chown -R "$username":"$username" "/home/$username"
chmod -R +x "/home/$username/.config/i3/scripts"
if [ -f "/home/$username/set_once.sh" ]; then chmod +x "/home/$username/set_once.sh"; fi
# Install packages using dnf (Fedora package manager)
# packages-fedora.txt contains Fedora-compatible package names
mapfile -t PACKAGES < <(grep -v '^#' "${REPO_FULL_PATH}/packages-fedora.txt" | grep -v '^[[:space:]]*$')
dnf install -y "${PACKAGES[@]}"
rm -rf "${REPO_FULL_PATH}"
systemctl enable lightdm
