#!/usr/bin/env bash
# Maintainer: joekamprad [joekamprad //a_t// endeavouros.com]
# Adapted for Fedora
REPO_DIR="endeavouros-i3wm-setup-for-fedora"
git clone https://github.com/Leandro-Michail-Krikis/endeavouros-i3wm-setup-for-fedora.git
cd "${REPO_DIR}/etc/skel/" || exit 1
cp -R .config .local ~/
chmod -R +x ~/.config/i3/scripts
cp .Xresources .profile .gtkrc-2.0 ~/
if [ -f set_once.sh ]; then cp set_once.sh ~/; fi
if [ -f xed.dconf ]; then
    cp xed.dconf ~/
    dbus-launch dconf load / < ~/xed.dconf
    rm ~/xed.dconf
fi
cd ../.. || exit 1
# Install packages using dnf (Fedora package manager)
# packages-fedora.txt contains Fedora-compatible package names
mapfile -t PACKAGES < <(grep -v '^#' "${REPO_DIR}/packages-fedora.txt" | grep -v '^[[:space:]]*$')
sudo dnf install -y "${PACKAGES[@]}"
rm -rf "${REPO_DIR}"
